#!/bin/bash
#/home/nmaster/git_one/News-Box-Application/dmzAPI/firewallsetup/firewall-down
#/home/nmaster/git_one/News-Box-Application/dmzAPI/firewallsetup/firewall


sudo ./firewall-down
sudo ./firewall
