#!/bin/bash
#
# iptables example configuration script

 


# Other rules for future use if needed.  Uncomment to activate
/sbin/iptables -A INPUT -p tcp --dport 80 -m state --state NEW -j ACCEPT    # http
/sbin/iptables -A INPUT -p tcp --dport 443 -m state --state NEW -j ACCEPT   # https
/sbin/iptables -A INPUT -p tcp --dport 5672 -m state --state NEW -j ACCEPT  # rabbit



# Allow pinging of your server
/sbin/iptables -A INPUT -p icmp --icmp-type 8 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT


# Drop all other traffic
/sbin/iptables -A INPUT -j DROP


# print the activated rules to the console when script is completed
/sbin/iptables -nL
